# Generated by Django 3.1.6 on 2021-03-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=50)),
                ('no_of_terms', models.IntegerField(default=20)),
            ],
        ),
    ]
